Issue127 fix shuffle animation
JMCanning78/datastructures-visualization pull request #128
Opened 2020-08-05 22:23 UTC by JMCanning78

I changed the shuffle animation algorithm to a velocity-based approach to close #127.   Each cell starts with a random velocity vector that pushes it away from its starting position, down, and towards its target position (using the `random.shuffle()` permutation to determine the new position).  The velocity vector is adjusted on each animation iteration to point more and more towards the target, with some added random jitter.  The path for an individual element is sort of a spiral to its final location in the array.

Also: 
  * Prepared code for drawable's display_shape or display_val field being `None`.
  * Fixed extraction of color attribute from itemconfiguration calls.

2020-10-18 23:02 UTC, lilypolonetsky requested changes
Aside from the extra closed parentheses, this looks great! I tested out the shuffle with resized windows and there was no error.

One other thought - I think the missing [-1] after `itemconfigure(cellPair[0], 'fill')` may also be in other parts of the code (since much was based off of SimpleSorting.py). Should we open an issue to deal with this?

2020-10-19 04:21 UTC, JMCanning78 commented on PythonVisualizations/SimpleSorting.py
> +            for i in range(nItems)):
I fixed the extra parenthesis on line 399 in commit c5ba1e2 .  I couldn't find any calls to `itemconfigure()` that were missing a [-1] to extract the last item, so I skipped that.  I did merge in the changes from the `master` branch to resolve the one conflict that had arose.

2020-10-19 04:22 UTC, JMCanning78 commented
I think I fixed the problems mentioned in [your comment](https://github.com/JMCanning78/datastructures-visualization/pull/128#pullrequestreview-511267385), Lily.

2020-10-19 17:43 UTC, lilypolonetsky approved these changes
Looks great!

2020-10-19 23:21 UTC, merged